CREATE TABLE IF NOT EXISTS `entity` (
  `id` varchar(16) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  `ident` varchar(80) DEFAULT NULL,
  `vhost` varchar(512) DEFAULT NULL,
  `db_name` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  `db_host` varchar(255) NOT NULL DEFAULT '',
  `fs_host` varchar(255) NOT NULL DEFAULT '',
  `home_dir` varchar(512) NOT NULL DEFAULT '',
  `home_id` varchar(16) DEFAULT NULL,
  `default_lang` varchar(12) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT 'en',
  `home_layout` varchar(128) NOT NULL DEFAULT '',
  `homepage` varchar(1600) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '{}' COMMENT 'TO BE REMOVED',
  `overview` mediumtext DEFAULT NULL,
  `layout` mediumtext DEFAULT NULL COMMENT 'TO BE REMOVED',
  `type` enum('organization','hub','drumate','shop','blog','forum','guest','dummy') DEFAULT NULL,
  `area` enum('public','share','limited','restricted','private','personal','system','dummy','dmz-public','dmz-private','dmz','pool','pool/dmz','template') DEFAULT NULL,
  `domain` varchar(255) DEFAULT NULL,
  `area_id` varbinary(16) DEFAULT NULL,
  `dom_id` int(11) unsigned DEFAULT NULL,
  `headline` varchar(255) DEFAULT NULL,
  `status` enum('active','frozen','deleted','archived','system','locked','online','offline','hidden') DEFAULT NULL,
  `accessibility` enum('open','membership','personal') DEFAULT 'open',
  `ctime` int(11) unsigned NOT NULL,
  `mtime` int(11) unsigned NOT NULL,
  `space` float NOT NULL DEFAULT 0,
  `menu` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci DEFAULT NULL COMMENT 'Pointer to the default menu',
  `settings` mediumtext NOT NULL,
  `icon` varchar(500) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT 'https://fonts.drumee.name/static/images/drumee/logo.png',
  `frozen_time` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `db_name` (`db_name`),
  UNIQUE KEY `home_dir` (`home_dir`),
  UNIQUE KEY `home_id` (`home_id`),
  KEY `category` (`type`),
  KEY `ctime` (`ctime`,`mtime`),
  KEY `home_layout` (`home_layout`),
  KEY `status` (`status`),
  KEY `area_id` (`area_id`),
  KEY `default_lang` (`default_lang`),
  KEY `icon` (`icon`),
  FULLTEXT KEY `settings` (`settings`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
