CREATE TABLE IF NOT EXISTS `hub` (
  `sys_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `id` varchar(16) CHARACTER SET ascii COLLATE ascii_general_ci DEFAULT NULL,
  `hubname` varchar(80) DEFAULT NULL,
  `domain_id` int(10) unsigned DEFAULT NULL,
  `owner_id` varchar(16) CHARACTER SET ascii COLLATE ascii_general_ci DEFAULT NULL,
  `origin_id` varchar(16) DEFAULT NULL,
  `dmail` varchar(255) NOT NULL DEFAULT '',
  `name` varchar(80) NOT NULL,
  `serial` int(11) unsigned NOT NULL DEFAULT 0,
  `description` varchar(2000) DEFAULT NULL,
  `keywords` varchar(2000) DEFAULT NULL,
  `permission` tinyint(4) unsigned NOT NULL DEFAULT 0,
  `profile` mediumtext DEFAULT NULL,
  PRIMARY KEY (`sys_id`),
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `_ident` (`hubname`),
  UNIQUE KEY `serial` (`owner_id`,`serial`),
  KEY `dmail` (`dmail`),
  KEY `default_perm` (`permission`),
  KEY `owner_id` (`owner_id`),
  KEY `origin_id` (`origin_id`),
  FULLTEXT KEY `keywords` (`name`,`keywords`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
