
# -------------------------------------------------------------
# !!!!!!! DO NOT EDIT !!!!!!!!
# Config file automatically generated by <setup-infra>
# Purpose     : Vendors surface — same backend as <%= public_domain %>,
#               served under its own name so it carries its own certificate.
# Server name : <%= vendors_public_domain %>
# Date        : <%= date %>
# -------------------------------------------------------------

server {
	listen <%= public_http_port %>;
	listen [::]:<%= public_http_port %>;
	server_name <%= vendors_public_domain %> *.<%= vendors_public_domain %>;
	location / {
		return  301 https://$host$request_uri;
	}
}
server {
	listen <%= public_https_port %> ssl;
	listen [::]:<%= public_https_port %> ssl;
	#
	root <%= server_dir %>;
	server_name <%= vendors_public_domain %> *.<%= vendors_public_domain %>;
	client_max_body_size <%= max_body_size %>;

	# Security headers
	add_header X-Content-Type-Options nosniff;
	add_header X-XSS-Protection "1; mode=block";

	set $prefix "";

	include /etc/drumee/ssl/vendors.public.conf;
	# Identical routing to 01-public.conf: the vendors names reach the SAME
	# backend, they are only a distinct entry point (and a distinct certificate).
	include /etc/drumee/infrastructure/routes/*.conf;
	include /etc/drumee/infrastructure/internals/accel.public.conf;
	include /etc/drumee/infrastructure/mfs.public.conf;
}
