# -------------------------------------------------------------
# !!!!!!! DO NOT EDIT !!!!!!!!
# Config file automatically generated by <setup-infra>
# Purpose     : Provide Nginx config to a specific server
# Server name : <%= domain %>
# Date        : <%= date %>
# -------------------------------------------------------------

map $http_upgrade $connection_upgrade {
	default upgrade;
	''      close;
}

server {
	listen <%= public_http_port %> default_server;
	listen [::]:<%= public_http_port %> default_server;
	# http2 on;
    server_name *.<%= jitsi_public_domain %>;
	include /etc/jitsi/meet.public.conf;
}

server {
	listen <%= public_https_port %> ssl ;
	listen [::]:<%= public_https_port %> ssl;
	# http2 on;
	server_name <%= jitsi_public_domain %>; 
	include /etc/jitsi/ssl.public.conf;
	include /etc/jitsi/meet.public.conf;
}

