# -------------------------------------------------------------
# !!!!!!! DO NOT EDIT !!!!!!!!
# Config file automatically generated by <setup-infra>
# Purpose     : Provide Nginx config to a specific server
# Server name : <%= domain %>
# Date        : <%= date %>
# -------------------------------------------------------------

map $http_upgrade $connection_upgrade {
	default upgrade;
	''      close;
}

server {
	listen <%= http_port %> default_server;
	listen [::]:<%= http_port %> default_server;
    server_name *.<%= jitsi_domain %>;
	include /etc/jitsi/meet.conf;
}

server {
	listen <%= https_port %> ssl http2;
	listen [::]:<%= https_port %> ssl http2;
	server_name <%= jitsi_domain %>; 
	include /etc/jitsi/ssl.conf;
	include /etc/jitsi/meet.conf;
}

