
# -------------------------------------------------------------
# !!!!!!! DO NOT EDIT !!!!!!!!
# Config file automatically generated by <setup-infra>
# Purpose     : Provide Nginx config to a specific server
# Server name : <%= private_domain %>
# Date        : <%= date %>
# -------------------------------------------------------------


proxy_cache_path <%= cache_dir %>/<%= private_domain %> levels=1:2 keys_zone=<%= private_domain %>_keys_zone:10m max_size=10g inactive=60m;
server {
	listen <%= http_port %>;
	listen [::]:<%= http_port %>;
	server_name <%= private_domain %>; 
	location / {
		return  301 https://$host$request_uri;
	}
}
server {
	listen <%= https_port %> ssl;
	listen [::]:<%= https_port %> ssl;	
	#
	root <%= server_dir %>;
	server_name <%= private_domain %>; 
	client_max_body_size <%= max_body_size %>;

	# Security headers
	add_header X-Content-Type-Options nosniff;
	add_header X-XSS-Protection "1; mode=block";

	set $prefix "";

	include /etc/drumee/ssl/private.conf;
	include /etc/drumee/infrastructure/routes/*.conf;
	include /etc/drumee/infrastructure/internals/*.conf;
	include /etc/drumee/infrastructure/mfs.conf;
}


