Document: drumee
Title: Drumee Schemas Manual
Author: <somanos@drumee.net>
Abstract: Drumee Schemas manual.
Section: non-free

Format: debiandoc-sgml
Files: /usr/share/doc/drumee/drumee-schemas.sgml.gz

Format: postscript
Files: /usr/share/doc/drumee/drumee-schemas.ps.gz

Format: text
Files: /usr/share/doc/drumee/drumee-schemas.text.gz

Format: HTML
Index: /usr/share/doc/drumee-schemas/html/index.html
Files: /usr/share/doc/drumee-schemas/html/*.html
