DELIMITER $

DROP FUNCTION IF EXISTS `is_socket_bound`$
CREATE FUNCTION  `is_socket_bound`(
  _sid VARCHAR(80) CHARACTER SET ascii,
  _cid VARCHAR(80) CHARACTER SET ascii
)
RETURNS INTEGER DETERMINISTIC
BEGIN
  DECLARE _r INTEGER DEFAULT 0;
  SELECT COUNT(*) FROM socket WHERE cookie=_cid AND id=_sid INTO _r;
  RETURN _r;
END$

DELIMITER ;
