# -------------------------------------------------------------
# ! DO NOT EDIT !
# Config file automatically generated by <setup-infra>
# Date : <%= date %>
# -------------------------------------------------------------
#
# The application routes, rendered ONCE and shared by every vhost.
#
# Every server block does `include /etc/drumee/infrastructure/routes/*.conf`, so
# this directory may only hold files whose location prefixes do not overlap —
# additive modules (jitsi, vendors, …) that own their own paths. It replaces the
# former public.conf/private.conf pair, which were not modules at all but two
# renderings of THIS route set for two different server blocks. Both declared
# `location /-/`, so on an instance with a public and a private domain the glob
# pulled both into one server block and nginx refused the entire configuration:
#
#   nginx: [emerg] duplicate location "/-/" in .../routes/public.conf:45
#
# A single-domain install renders only one of the two, which is why it looked
# correct for so long.
#
# Do NOT reintroduce a per-domain variant here. The two differed in exactly two
# ways, neither of which needed its own file:
#
#   * Access-Control-Allow-Origin, hardcoded to the vhost's domain. A bare
#     hostname is not a valid CORS origin — it needs a scheme — so both variants
#     were inert and every browser ignored them. `$scheme://$host` is valid,
#     echoes whichever name was requested, and is therefore correct for the
#     public, private, vendors and jit vhosts alike. It cannot be `*`: the index
#     location sends Access-Control-Allow-Credentials, and the two are mutually
#     exclusive.
#   * `proxy_set_header Referer`, present only on the public side. Kept for both;
#     the backend either uses it or ignores it.
#
# What remains is domain-independent by construction — date, location, ports,
# ui_location, ui_plugins_home — which is what makes one rendering sufficient.


location <%= location %>app/ {
  alias <%= ui_location %>/app/;
  add_header Cache-Control max-age=31536000;
  add_header Access-Control-Allow-Origin $scheme://$host;
  fastcgi_hide_header Set-Cookie;
  break;
}

# Frontend application assets
location <%= location %>api/ {
  alias <%= ui_location %>/api/;
  add_header Cache-Control max-age=31536000;
  add_header Access-Control-Allow-Origin $scheme://$host;
  fastcgi_hide_header Set-Cookie;
  break;
}

# Frontend application assets
location <%= location %>plugins/ {
  alias <%= ui_plugins_home %>/;
  add_header Cache-Control max-age=31536000;
  add_header Access-Control-Allow-Origin $scheme://$host;
  fastcgi_hide_header Set-Cookie;
  break;
}


# Frontend application templates
location <%= location %>bb-templates/ {
  alias  <%= ui_location %>/bb-templates/;
  add_header Cache-Control max-age=31536000;
  add_header Access-Control-Allow-Origin *;
  fastcgi_hide_header Set-Cookie;
  break;
}


location <%= location %> {
  fastcgi_hide_header Set-Cookie;
  add_header Cache-Control max-age=31536000;

  location ~ /(svc|vdo|service)/ {
    proxy_pass http://<%= backend_host %>:<%= restPort %>;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Connecting-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header Referer $http_referer;
    add_header Vary "Accept-Encoding";
    fastcgi_hide_header Set-Cookie;
    break;
  }

  location ~ /(ws|websocket)/ {
    proxy_pass http://<%= backend_host %>:<%= pushPort %>;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Connecting-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header Referer $http_referer;
    add_header Vary "Accept-Encoding";
    fastcgi_hide_header Set-Cookie;
    break;
  }

#------------ parts/apis ------------
  location ~ /file/(.+)/(.*)$ {
    fastcgi_hide_header Set-Cookie;
    rewrite /file/(.+)/(.+)/(.+)\.(.*)$ /-/svc/media.$1?nid=$2&hub_id=$3 last;
    rewrite /file/(.+)/(.+)/(.+)/(.*)$ /-/svc/media.$1?nid=$2&hub_id=$3 last;
    rewrite /file/(.+)/(.+)/(.+)$ /-/svc/media.$1?nid=$2&hub_id=$3 last;
    rewrite /file/(.+)/(.+)\.(.+)$ /-/svc/media.$1?nid=$2 last;
    rewrite /file/(.+)/(.+)$ /-/svc/media.$1?nid=$2 last;
    break;
  }


  location ~ /doc/(.+)/(.*)$ {
    add_header Cache-Control max-age=31536000;
    fastcgi_hide_header Set-Cookie;
    rewrite /doc/(.+)/(.+)/(.+)\.(.*)$ /-/svc/media.read?page=$1&nid=$2&hub_id=$3 last;
    rewrite /doc/(.+)/(.+)/(.+)$ /-/svc/media.read?page=$1&nid=$2&hub_id=$3 last;
    rewrite /doc/(.+)/(.+)\.(.+)$ /-/svc/media.read?page=$1&nid=$2 last;
    rewrite /doc/(.+)/(.+)$ /-/svc/media.read?page=$1&nid=$2 last;
    break;
  }

  location ~ /letc/(.+)$ {
    add_header Cache-Control max-age=31536000;
    fastcgi_hide_header Set-Cookie;
    rewrite /letc/(.+)\@(.+)$ /-/svc/block.content?hashtag=$1&owner=$2 last;
    rewrite /letc/(.+)/(.+)$ /-/svc/block.content?hashtag=$1&owner=$2 last;
    rewrite /letc/(.+)$ /-/svc/block.content?hashtag=$1 last;
    break;
  }


  location ~ /avatar/(.+)$ {
    add_header Pragma public;
    add_header Cache-Control max-age=31536000;
    fastcgi_hide_header Set-Cookie;
    add_header Access-Control-Allow-Origin $scheme://$host;
    rewrite /avatar/(.+)$ /-/svc/yp.avatar?id=$1 last;
    break;
  }

  location ~ (.+)\.(.+)$ {
    fastcgi_hide_header Set-Cookie;
    add_header Cache-Control max-age=31536000;
    add_header Access-Control-Allow-Origin $scheme://$host;
    rewrite /somanos/(.+)$ /-/svc/media.raw&p=$1&d=inline;
    break;
  }

#------------ parts/index ------------
  location ~ (/|)$ {
    proxy_pass http://<%= backend_host %>:<%= pushPort %>;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Connecting-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header Referer $http_referer;
    add_header Access-Control-Allow-Credentials true;
    add_header Vary "Accept-Encoding";
    fastcgi_hide_header Set-Cookie;
  }

}
