# -------------------------------------------------------------
# ! DO NOT EDIT !
# Config file automatically generated by <setup-infra>
# Date : <%= date %>
# -------------------------------------------------------------


location <%= location %>app/ {
  alias <%= drumee_root %>/runtime/ui/<%= endpoint_name %>/app/;
  add_header Cache-Control max-age=31536000;
  add_header Access-Control-Allow-Origin <%= domain %>;
  fastcgi_hide_header Set-Cookie;
  break;
}

# Frontend application assets
location <%= location %>api/ {
  alias <%= drumee_root %>/runtime/ui/<%= endpoint_name %>/api/;
  add_header Cache-Control max-age=31536000;
  add_header Access-Control-Allow-Origin <%= domain %>;
  fastcgi_hide_header Set-Cookie;
  break;
}

# Frontend application assets
location 
plugins/ {
  alias <%= drumee_root %>/runtime/ui/<%= endpoint_name %>/plugins/;
  add_header Cache-Control max-age=31536000;
  add_header Access-Control-Allow-Origin <%= domain %>;
  fastcgi_hide_header Set-Cookie;
  break;
}


# Frontend application templates
location <%= location %>bb-templates/ {
  alias  <%= drumee_root %>/runtime/ui/<%= endpoint_name %>/bb-templates/;
  add_header Cache-Control max-age=31536000;
  add_header Access-Control-Allow-Origin *;
  fastcgi_hide_header Set-Cookie;
  break;
}


location <%= location %> {
  fastcgi_hide_header Set-Cookie;
  add_header Cache-Control max-age=31536000;

  location ~ /(svc|vdo|service)/ {
    proxy_pass http://<%= backend_host %>:<%= restPort %>;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Connecting-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Port $server_port;  # The port Nginx is listening on
    proxy_set_header X-Original-Port $http_host;
    add_header Vary "Accept-Encoding";
    fastcgi_hide_header Set-Cookie;
    break;
  }

  location ~ /(ws|websocket)/ {
    proxy_pass http://<%= backend_host %>:<%= pushPort %>;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Connecting-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Port $server_port;  # The port Nginx is listening on
    proxy_set_header X-Original-Port $http_host;
    add_header Vary "Accept-Encoding";
    fastcgi_hide_header Set-Cookie;
    break;
  }

#------------ parts/apis ------------
  location ~ /file/(.+)/(.*)$ {
    fastcgi_hide_header Set-Cookie;
    rewrite /file/(.+)/(.+)/(.+)\.(.*)$ /-/svc/media.$1?nid=$2&hub_id=$3 last;
    rewrite /file/(.+)/(.+)/(.+)/(.*)$ /-/svc/media.$1?nid=$2&hub_id=$3 last;
    rewrite /file/(.+)/(.+)/(.+)$ /-/svc/media.$1?nid=$2&hub_id=$3 last;
    rewrite /file/(.+)/(.+)\.(.+)$ /-/svc/media.$1?nid=$2 last;
    rewrite /file/(.+)/(.+)$ /-/svc/media.$1?nid=$2 last;
    break;
  }


  location ~ /doc/(.+)/(.*)$ {
    add_header Cache-Control max-age=31536000;
    fastcgi_hide_header Set-Cookie;
    rewrite /doc/(.+)/(.+)/(.+)\.(.*)$ /-/svc/media.read?page=$1&nid=$2&hub_id=$3 last;
    rewrite /doc/(.+)/(.+)/(.+)$ /-/svc/media.read?page=$1&nid=$2&hub_id=$3 last;
    rewrite /doc/(.+)/(.+)\.(.+)$ /-/svc/media.read?page=$1&nid=$2 last;
    rewrite /doc/(.+)/(.+)$ /-/svc/media.read?page=$1&nid=$2 last;
    break;
  }

  location ~ /letc/(.+)$ {
    add_header Cache-Control max-age=31536000;
    fastcgi_hide_header Set-Cookie;
    rewrite /letc/(.+)\@(.+)$ /-/svc/block.content?hashtag=$1&owner=$2 last;
    rewrite /letc/(.+)/(.+)$ /-/svc/block.content?hashtag=$1&owner=$2 last;
    rewrite /letc/(.+)$ /-/svc/block.content?hashtag=$1 last;
    break;
  }


  location ~ /avatar/(.+)$ {
    add_header Pragma public;
    add_header Cache-Control max-age=31536000;
    fastcgi_hide_header Set-Cookie;
    add_header Access-Control-Allow-Origin <%= domain %>;
    rewrite /avatar/(.+)$ /-/svc/yp.avatar?id=$1 last;
    break;
  }

  location ~ (.+)\.(.+)$ {
    fastcgi_hide_header Set-Cookie;
    add_header Cache-Control max-age=31536000;
    add_header Access-Control-Allow-Origin <%= domain %>;
    rewrite /<%= endpoint_name %>/(.+)$ /-/svc/media.raw&p=$1&d=inline;
    break;
  }


#------------ parts/index ------------
  location ~ (/|)$ {
    proxy_pass http://<%= backend_host %>:<%= pushPort %>;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Connecting-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Port $server_port;  # The port Nginx is listening on
    proxy_set_header X-Original-Port $http_host;
    proxy_set_header Referer $http_referer;
    proxy_set_header X-Forwarded-Proto $scheme;
    add_header Access-Control-Allow-Credentials true;
    add_header Vary "Accept-Encoding";
    fastcgi_hide_header Set-Cookie;
  }

}
