CREATE TABLE IF NOT EXISTS `layout` (
  `sys_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `id` varbinary(16) NOT NULL,
  `author_id` varbinary(16) NOT NULL,
  `hashtag` varchar(500) NOT NULL,
  `type` enum('page','block','menu','header','footer','slider','gallery') NOT NULL DEFAULT 'block',
  `context` enum('page','slider','slideshow','menu','creator','designer') NOT NULL DEFAULT 'creator',
  `editor` enum('designer','creator') CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT 'creator',
  `tag` varchar(400) NOT NULL,
  `hash` varchar(500) DEFAULT NULL,
  `device` varchar(2000) DEFAULT NULL,
  `lang` varchar(2000) DEFAULT NULL,
  `author` varchar(80) DEFAULT NULL,
  `comment` varchar(1024) DEFAULT NULL,
  `content` mediumtext DEFAULT NULL,
  `footnote` mediumtext DEFAULT NULL,
  `backup` mediumtext DEFAULT NULL,
  `newbie` mediumtext DEFAULT NULL,
  `expert` mediumtext DEFAULT NULL,
  `status` enum('active','deleted','locked','backup','readonly','draft','exported') DEFAULT NULL,
  `ctime` int(11) NOT NULL,
  `mtime` int(11) NOT NULL,
  `version` varchar(10) NOT NULL DEFAULT '1.0.0',
  PRIMARY KEY (`sys_id`),
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `id_2` (`id`),
  UNIQUE KEY `hashtag` (`hashtag`),
  UNIQUE KEY `hash` (`hash`) USING BTREE,
  KEY `author` (`author`),
  KEY `ctime` (`ctime`),
  KEY `mtime` (`mtime`),
  KEY `version` (`version`),
  KEY `ltype` (`context`),
  KEY `tag` (`tag`),
  KEY `author_id` (`author_id`),
  KEY `editor` (`editor`),
  FULLTEXT KEY `content` (`content`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
