// Container PM2 config for server-pod. The component repo ships index.js
// (page serving + WebSocket) and service.js (REST API) but no committed
// ecosystem file (it's generated by dev-tools at deploy), so the image ships
// this one. pm2-runtime keeps both processes in the foreground as PID 1.
//
// index.js / service.js parse their OWN CLI args (configs.js, argparse):
//   --pushPort  page + WebSocket listener (default 23000)  -> index.js
//   --restPort  REST API listener        (default 24000)  -> service.js
//   --http-port / --https-port           (default 80/443)
//   --conf-path dir containing etc/drumee/conf.d
// These MUST be passed as args or the scripts exit with "unrecognized arguments".
// Values come from the rendered .env (UI_PORT=pushPort, API_PORT=restPort).
const APP = (process.env.DRUMEE_SERVER_HOME || '/srv/drumee/runtime/server') + '/main';
const PUSH_PORT = process.env.UI_PORT || 23000;
const REST_PORT = process.env.API_PORT || 24000;
const HTTP_PORT = process.env.HTTP_PORT || 80;
const HTTPS_PORT = process.env.HTTPS_PORT || 443;
const CONF_PATH = process.env.CONF_PATH || '/';

// Container-idiomatic logging: pm2-runtime already streams app output to the
// container's stdout/stderr (where Docker handles rotation/retention). Disable
// pm2's duplicate file logs, which would grow unbounded inside the container.
const NO_FILE_LOGS = { out_file: '/dev/null', error_file: '/dev/null' };

module.exports = {
  apps: [
    {
      name: 'index',          // page serving + WebSocket
      script: 'index.js',
      cwd: APP,
      args: `--http-port ${HTTP_PORT} --https-port ${HTTPS_PORT} --pushPort ${PUSH_PORT} --conf-path ${CONF_PATH}`,
      // fork (NOT cluster): index.js/service.js parse process.argv via argparse;
      // cluster workers inherit pm2's argv and reject "start ecosystem.config.js".
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      env: { NODE_ENV: 'production' },
      ...NO_FILE_LOGS,
    },
    {
      name: 'service',        // REST API (/-/svc/module.method)
      script: 'service.js',
      cwd: APP,
      args: `--restPort ${REST_PORT} --conf-path ${CONF_PATH}`,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      env: { NODE_ENV: 'production' },
      ...NO_FILE_LOGS,
    },
  ],
};
