DELIMITER $
DROP FUNCTION IF EXISTS `entity_db`$
CREATE FUNCTION `entity_db`(
  _id VARCHAR(160)
)
RETURNS VARCHAR(30) DETERMINISTIC
BEGIN
  DECLARE _r VARCHAR(30);
  SELECT db_name FROM entity WHERE id=_id INTO _r;
  RETURN _r;
END$

DELIMITER ;
