-- -------------------------------------------------------------
-- ! DO NOT EDIT !
-- Config file automatically generated by <setup-infra>
-- Date : <%= date %>
-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `configs` (
  `name` varchar(64) NOT NULL DEFAULT '',
  `value` varchar(2048) DEFAULT NULL,
  `type` varchar(64) NOT NULL DEFAULT '',
  PRIMARY KEY (`name`)
) ENGINE=MEMORY DEFAULT CHARSET=utf8;

replace into configs values('db_host', "localhost", 'varchar');
replace into configs values('fs_host', "localhost", 'varchar');
replace into configs values('icon', "<%= default_ico %>/", 'varchar');
replace into configs values('page_length', '15', 'integer');
replace into configs values('mfs_root', "<%= data_dir %>/mfs/", 'varchar');

