#!/bin/sh
set +e

# Source debconf library
. /usr/share/debconf/confmodule

# Ask questions
db_input high mypackage/domain || true
db_input high mypackage/partition || true
db_go

# Get answers
db_get mypackage/domain
DOMAIN=$RET
db_get mypackage/partition
PARTITION=$RET

# Use the answers, for example:
echo "Domain: $DOMAIN"
echo "Partition: $PARTITION"

# Don't forget to cleanup
db_stop

# End of script
exit 0
