Document: drumee
Title: Drumee Server Manual
Author: <somanos@drumee.net>
Abstract: Drumee Server manual.
Section: non-free

Format: debiandoc-sgml
Files: /usr/share/doc/drumee/drumee.sgml.gz

Format: postscript
Files: /usr/share/doc/drumee/drumee.ps.gz

Format: text
Files: /usr/share/doc/drumee/drumee.text.gz

Format: HTML
Index: /usr/share/doc/drumee/html/index.html
Files: /usr/share/doc/drumee/html/*.html
