# -------------------------------------------------------------
# ! DO NOT EDIT !
# Config file automatically generated by <setup-infra>
# -------------------------------------------------------------
export OVH_AK=<%= appKey %>
export OVH_CK=<%= consumerKey %>
export OVH_AS=<%= appSecret %>
