# -------------------------------------------------------------
# ! DO NOT EDIT !
# Config file automatically generated by <setup-infra>
# Date : <%= date %>
# -------------------------------------------------------------

ssl_certificate <%= certs_dir %>/<%= public_domain %>_ecc/fullchain.cer;
ssl_trusted_certificate <%= certs_dir %>/<%= public_domain %>_ecc/ca.cer;
ssl_certificate_key <%= certs_dir %>/<%= public_domain %>_ecc/<%= public_domain %>.key;

