# -------------------------------------------------------------
# ! DO NOT EDIT !
# Config file automatically generated by <setup-infra>
# Date : <%= date %>
# -------------------------------------------------------------
#
# The vendors surface has its OWN certificate rather than reusing the apex one:
# a wildcard matches exactly one label, so *.<%= public_domain %> covers
# <%= vendors_public_domain %> but nothing below it. Issued by
# bin/init-acme (make_certs <%= vendors_public_domain %>), which requests both
# <%= vendors_public_domain %> and *.<%= vendors_public_domain %>.

ssl_certificate <%= certs_dir %>/<%= vendors_public_domain %>_ecc/fullchain.cer;
ssl_trusted_certificate <%= certs_dir %>/<%= vendors_public_domain %>_ecc/ca.cer;
ssl_certificate_key <%= certs_dir %>/<%= vendors_public_domain %>_ecc/<%= vendors_public_domain %>.key;
