ALTER TABLE `cookie`
  ADD COLUMN IF NOT EXISTS `priv_ceiling` TINYINT UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `ceiling_uid` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_general_ci DEFAULT NULL;
