export DRUMEE_INSTALL=auto
export DRUMEE_DOMAIN_NAME=red-chipie.com
export DRUMEE_SERVER_ROOT=/home/somanos/tmp/server-root
export DRUMEE_DATA_DIR=/your/drumee/data/volume
export ACME_DNS=ovh
export ACME_EMAIL_ACCOUNT=your-acme@account.mail
export DRUMEE_EXPORT_DIR=/your/export/dir
export DRUMEE_IMPORT_DIR=/your/import/dir
export DRUMEE_INSTANCE_NAME="Your Drumee Instance"
export DRUMEE_EMAIL_PASS="random"
export DRUMEE_DB_PASS="random"
export DRUMEE_POOL_SIZE=4
export ACME_DIR=/home/somanos/tmp/acme
