DELIMITER $
DROP FUNCTION IF EXISTS `uniqueId`$
CREATE FUNCTION `uniqueId`(

)
RETURNS VARCHAR(16) DETERMINISTIC
BEGIN
  DECLARE _res VARCHAR(16);
  SELECT CONCAT(
    SUBSTRING_INDEX(UUID(), '-', 1),
    SUBSTRING_INDEX(UUID(), '-', 1)
  ) INTO _res;
  RETURN _res;
END$
DELIMITER ;
