DROP TABLE IF EXISTS `trash_media`;
CREATE TABLE IF NOT EXISTS `trash_media` (
  `sys_id` int(11) unsigned NOT NULL,
  `id` varchar(16) CHARACTER SET ascii COLLATE ascii_general_ci DEFAULT NULL,
  `origin_id` varchar(16) CHARACTER SET ascii COLLATE ascii_general_ci DEFAULT NULL,
  `owner_id` varchar(16) CHARACTER SET ascii COLLATE ascii_general_ci DEFAULT NULL,
  `host_id` varchar(16) CHARACTER SET ascii COLLATE ascii_general_ci DEFAULT NULL,
  `file_path` varchar(1000) DEFAULT NULL,
  `user_filename` varchar(128) DEFAULT NULL,
  `parent_id` varchar(16) CHARACTER SET ascii COLLATE ascii_general_ci DEFAULT NULL,
  `parent_path` varchar(1024) NOT NULL,
  `extension` varchar(100) CHARACTER SET ascii COLLATE ascii_general_ci DEFAULT NULL,
  `mimetype` varchar(100) NOT NULL,
  `category` varchar(16) NOT NULL DEFAULT 'other',
  `isalink` tinyint(2) unsigned NOT NULL DEFAULT 0,
  `filesize` bigint(20) unsigned DEFAULT 0,
  `geometry` varchar(200) NOT NULL DEFAULT '0x0',
  `publish_time` int(11) unsigned NOT NULL DEFAULT 0,
  `upload_time` int(11) unsigned NOT NULL DEFAULT 0,
  `trashed_time` INT(11) UNSIGNED NOT NULL DEFAULT 0, 
  `last_download` int(11) unsigned NOT NULL DEFAULT 0,
  `download_count` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `metadata` longtext DEFAULT NULL,
  `caption` varchar(1024) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `approval` enum('submitted','verified','validated','draft','online','offline') DEFAULT 'draft',
  `rank` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`sys_id`),
  UNIQUE KEY `id` (`id`),
  KEY `approval` (`approval`),
  KEY `geometry` (`geometry`),
  KEY `origin_id` (`origin_id`),
  KEY `file_path` (`file_path`(768)),
  KEY `user_filename` (`user_filename`),
  KEY `category` (`category`),
  KEY `parent_id` (`parent_id`),
  KEY `id_category` (`id`,`category`),
  KEY `idx_status` (`status`),
  KEY `idx_trashed_time` (`trashed_time`),
  FULLTEXT KEY `content` (`caption`,`user_filename`,`file_path`,`metadata`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
