DELIMITER $
DROP FUNCTION IF EXISTS `sys_conf_get`$
CREATE FUNCTION `sys_conf_get`(
  _key VARCHAR(1024)
)
RETURNS VARCHAR(1024) DETERMINISTIC
BEGIN
DECLARE _r LONGTEXT DEFAULT "";
  SELECT conf_value FROM sys_conf WHERE conf_key=_key INTO _r;
  RETURN _r;
END$

DELIMITER ;