#!/bin/bash
source /etc/drumee/drumee.sh
if [ ! -d $DRUMEE_SERVER_HOME ]; then
  echo "DRUMEE_SERVER_HOME is not set"
  exit 1
fi
if [ -z $DRUMEE_SYSTEM_USER ]; then
  DRUMEE_SYSTEM_USER=www-data
fi


manager() {
  if [ -d $DRUMEE_LOG_DIR ]; then
    su -s /bin/bash $DRUMEE_SYSTEM_USER -c "HOME=$DRUMEE_SERVER_HOME pm2 -o $DRUMEE_LOG_DIR/out.log -e $DRUMEE_LOG_DIR/err.log $*"
  else
    su -s /bin/bash $DRUMEE_SYSTEM_USER -c "HOME=$DRUMEE_SERVER_HOME pm2 $*"
  fi
}

cd $DRUMEE_SERVER_HOME
case "$1" in
start)
  if [ ! -d $DRUMEE_LOG_DIR ]; then
    mkdir -p $DRUMEE_LOG_DIR
    chown -R $DRUMEE_SYSTEM_USER:$DRUMEE_SYSTEM_GROUP $DRUMEE_LOG_DIR
  fi
  if [ -z $2 ]; then
    manager start ecosystem.config.js
  else
    manager start ecosystem.config.js --only $2
  fi
  ;;
restart | stop)
  if [ -z $2 ]; then
    manager $1 all
  else
    manager $1 $2
  fi
  ;;
delete | show | monitor | status)
  if [ -z $2 ]; then
    echo "$0 $1 : name or id must be specified"
  else
    manager $1 $2
  fi
  ;;
monit | dash | list)
  manager $1
  ;;
log)
  if [ -z $2 ]; then
    manager $1 production
  else
    manager $1 $2
  fi
  ;;
*)
  manager $*
  ;;
esac
exit 0
