# -------------------------------------------------------------
# ! DO NOT EDIT !
# Config file automatically generated by <setup-infra>
# Date : <%= date %>
# -------------------------------------------------------------

location / {
  index /-/;

  location ~ (.+)$ {
    add_header Cache-Control max-age=31536000;
    fastcgi_hide_header Set-Cookie;
    add_header Access-Control-Allow-Origin <%= domain %>;
    rewrite /(.+)$ <%= public_ui_root %>/svc/media.raw?p=/$1&d=inline;
  }
}
