# -------------------------------------------------------------
# ! DO NOT EDIT !
# Config file automatically generated by <setup-infra>
# Date : <%= date %>
# -------------------------------------------------------------

location / {
  location ~ (.+)\.(.+)$ {
    #expires 7d;
    add_header Cache-Control max-age=31536000;
    #add_header Vary "Accept-Encoding";
    fastcgi_hide_header Set-Cookie;
    add_header Access-Control-Allow-Origin <%= domain %>;
    rewrite /(.+)$ <%= public_ui_root %>/service/?service=media.raw&p=$1&d=inline;
  }
}
