# -------------------------------------------------------------
# ! DO NOT EDIT !
# Config file automatically generated by <setup-infra>
# Date : <%= date %>
# -------------------------------------------------------------

export CERTS_DIR=<%= certs_dir %>
export ACME_DIR=<%= acme_dir %>
export ACME_DNS=<%= acme_dns %>
export ACME_EMAIL_ACCOUNT=<%= acme_email_account %>
export DRUMEE_CACHE_DIR=<%= cache_dir %>
export DRUMEE_DATA_DIR=<%= data_dir %>
export DRUMEE_DOMAIN_NAME=<%= domain_name %>
export DRUMEE_LOG_DIR=<%= log_dir %>
export DRUMEE_MFS_DIR=<%= data_dir %>/mfs
export DRUMEE_RUNTIME_DIR=<%= runtime_dir %>
export DRUMEE_SCHEMAS_DIR=<%= runtime_dir %>/server/schemas
export DRUMEE_SERVER_HOME=<%= server_dir %>
export DRUMEE_SERVER_NODE=<%= runtime_dir %>/dist/main/node_modules
export DRUMEE_STATIC_DIR=<%= static_dir %>
export DRUMEE_SYSTEM_GROUP=<%= system_group %>
export DRUMEE_SYSTEM_USER=<%= system_user %>
export DRUMEE_TMP_DIR=<%= runtime_dir %>/tmp
export DRUMEE_UI_HOME=<%= runtime_dir %>/ui
export LE_WORKING_DIR=<%= acme_dir %>
export OWN_SSL_CERTS_DIR=<%= own_certs_dir %>
export OWN_SSL=<%= own_ssl %>
export PUBLIC_UI_ROOT=<%= public_ui_root %>
