# -------------------------------------------------------------
# ! DO NOT EDIT !
# Config file automatically generated by <setup-infra>
# Date : <%= date %>
# -------------------------------------------------------------

location /mfs/ {
  gzip off;
  internal;
  add_header Cache-Control max-age=31536000;
  add_header Content-Encoding $upstream_http_content_encoding;
  add_header Access-Control-Allow-Origin <%= domain %>;
  alias <%= data_dir %>/mfs/;
}

location /accel/ {
  gzip off;
  internal;
  add_header Cache-Control max-age=31536000;
  add_header Content-Encoding $upstream_http_content_encoding;
  add_header Access-Control-Allow-Origin *;
  alias <%= static_dir %>/;
}

location /-/static/ {
  gzip off;
  add_header Cache-Control max-age=31536000;
  add_header Content-Encoding $upstream_http_content_encoding;
  add_header Access-Control-Allow-Origin *;
  alias <%= static_dir %>/;
}

location /-/images/ {
  gzip off;
  add_header Cache-Control max-age=31536000;
  add_header Content-Encoding $upstream_http_content_encoding;
  add_header Access-Control-Allow-Origin *;
  alias <%= static_dir %>/images/;
}

location /-/fonts/ {
  gzip off;
  add_header Cache-Control max-age=31536000;
  add_header Content-Encoding $upstream_http_content_encoding;
  add_header Access-Control-Allow-Origin *;
  alias <%= static_dir %>/fonts/;
}
