DELIMITER $
DROP FUNCTION IF EXISTS `get_domain`$
CREATE FUNCTION `get_domain`(
  _ident VARCHAR(80)
)
RETURNS VARCHAR(512) DETERMINISTIC
BEGIN
  DECLARE _res VARCHAR(512);
  SELECT main_domain() INTO _res;
  RETURN _res;
END$
DELIMITER ;
